<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Introduction</name>
   <tag></tag>
   <elementGuidId>65be4fe9-17d5-4e7c-8d20-80e159e71efe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block-system-main-menu']/div/nav/ul/li[2]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nav.top-nav > ul > li.expanded.hasChildren > ul > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>17d4a71d-85c7-454f-9c85-366eb122cd17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/content/introduction</value>
      <webElementGuid>37e6a7be-372e-4411-82a9-3beb7f7e531b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Introduction</value>
      <webElementGuid>c268c357-1bb7-40c8-8581-e93e41b2bf63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-system-main-menu&quot;)/div[@class=&quot;content&quot;]/nav[@class=&quot;top-nav&quot;]/ul[1]/li[@class=&quot;expanded hasChildren&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>502531bb-7ebd-4d23-afef-9ef5fd921f04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-system-main-menu']/div/nav/ul/li[2]/ul/li/a</value>
      <webElementGuid>79215949-d649-43f3-9241-dde4b5cb8ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Introduction')])[2]</value>
      <webElementGuid>84c6dabf-572c-4f48-af64-cf14df399734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About DI'])[2]/following::a[1]</value>
      <webElementGuid>26b3e038-6c8a-48d1-86ae-f4d182633bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/following::a[2]</value>
      <webElementGuid>ed85b067-4c80-4f81-b10a-caf7282eaf1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vision and Vision Areas'])[2]/preceding::a[1]</value>
      <webElementGuid>7056e1ec-c56a-4f2d-a0c4-f7b00971625c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approach and Methodology'])[2]/preceding::a[2]</value>
      <webElementGuid>3ffa0123-bf69-4c25-9fcc-a3bb568f9184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/content/introduction')])[2]</value>
      <webElementGuid>828e1594-e9bb-4c4f-9f80-76e99fc70179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[2]/ul/li/a</value>
      <webElementGuid>e7e43d7a-6ce7-4942-914c-fa9ceb319815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/content/introduction' and (text() = 'Introduction' or . = 'Introduction')]</value>
      <webElementGuid>08009921-a866-4fa4-903c-3ae50c7ec9d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
