<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Feedback</name>
   <tag></tag>
   <elementGuidId>c3448ec9-3d86-4a93-9214-221f154bc969</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block-system-main-menu']/div/nav/ul/li[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nav.top-nav > ul > li.last.expanded.hasChildren > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>94feb6a8-f8d5-43c2-962a-662f16bdf4d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://digitalindia.gov.in/contact</value>
      <webElementGuid>5a247ace-d7e9-4704-9917-2c9acd1c237a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Feedback</value>
      <webElementGuid>d54dacb2-7e4b-421c-802c-067638c5c645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-system-main-menu&quot;)/div[@class=&quot;content&quot;]/nav[@class=&quot;top-nav&quot;]/ul[1]/li[@class=&quot;last expanded hasChildren&quot;]/a[1]</value>
      <webElementGuid>f528376c-7ffb-4bca-98c6-1b7ad7fa6343</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-system-main-menu']/div/nav/ul/li[7]/a</value>
      <webElementGuid>376072da-750d-429f-b08b-9b1fd5a93a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Feedback')])[3]</value>
      <webElementGuid>a318642e-8443-42d0-9dfa-4d0b9f8fb3f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RFPs/EOIS'])[2]/following::a[1]</value>
      <webElementGuid>97de2f00-5a43-469b-b027-051506cb54ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NeGD'])[2]/following::a[2]</value>
      <webElementGuid>10846e3a-6fb9-4abb-91d5-4c3f585f6d09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave Feedback'])[2]/preceding::a[1]</value>
      <webElementGuid>56d1f654-af67-4995-b548-449f3b11cfee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public Opinion/Survey'])[2]/preceding::a[2]</value>
      <webElementGuid>5eefd24c-bf03-41bb-bed9-73bb08b39f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://digitalindia.gov.in/contact')])[3]</value>
      <webElementGuid>e8e46f0d-c0c3-46d0-a7d8-926bc6d9f477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[7]/a</value>
      <webElementGuid>474c4349-aa59-4abe-ac14-29bc42a39e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://digitalindia.gov.in/contact' and (text() = 'Feedback' or . = 'Feedback')]</value>
      <webElementGuid>ce44b5da-fdce-46a1-8e0c-0e83111e0117</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
